# Generated by Django 3.2.8 on 2022-01-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
